# Generated by Django 5.1.3 on 2024-12-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0002_seat_route_seat_travel_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='time',
            field=models.CharField(max_length=15),
        ),
    ]
